### ISSUE TITLE
🐛 [BUG] - ActiveStorage::FileNotFoundError

### ISSUE THREAD

**Issue by ciscoLegrand** [CreadixGal/aeksion#107]
### Description

Cuando se crea o edita un producto con imagen, da un error 500 por culpa de active storage.
el producto lo crea pero redirige a error 500 porque algo falla al cargar las imagenes
es necesario revisar el dockerfile y la configuracion en el server para saber cual puede ser el motivo.
se añaden logs para mas informacion

### Reproduction URL

https://aeksion.fly.dev/products/ec2a4988-0445-49d0-9359-1fa7578b0a5f

### Reproduction steps

```bash
1. Go to 'productos'
2. Click on 'nuevo producto'
3. Rellenar los datos
4. Añadir imagen
5. Click on 'crear producto'
6. Redirects to 500 error page
```

### Logs

```bash
Waiting for logs...

2023-02-01T22:47:11.208 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.208479 #540] INFO -- : [d5a50b2a-8398-4fd7-a16c-e701a7003e45] Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWxpTm1aak5tTmhNUzFpTXpKaExUUmxOVGN0WW1GbU9DMWxOREptTVRZeU9EY3lNbVFHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--f8b936d063d7fe789af29e98b790aed2b718cc10", "variation_key"=>"[FILTERED]", "filename"=>"DP608"}

2023-02-01T22:47:11.213 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.212968 #540] INFO -- : [f4a13a63-e385-4b4f-aab7-987e00311d80] Disk Storage (0.2ms) Downloaded file from key: e8v1me4olm1yw7ly7gpgm7zu9xy2

2023-02-01T22:47:11.214 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.214137 #540] INFO -- : [f4a13a63-e385-4b4f-aab7-987e00311d80] Completed 500 Internal Server Error in 16ms (ActiveRecord: 1.7ms | Allocations: 8852)

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] F, [2023-02-01T22:47:11.214894 #540] FATAL -- : [f4a13a63-e385-4b4f-aab7-987e00311d80]

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80]

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:150:in `rescue in stream'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:143:in `stream'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:29:in `block in download'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service.rb:163:in `instrument'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:28:in `download'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/downloader.rb:32:in `download'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/downloader.rb:13:in `block in open'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/downloader.rb:24:in `open_tempfile'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/downloader.rb:12:in `open'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) lib/active_storage/service.rb:90:in `open'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) app/models/active_storage/blob.rb:301:in `open'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:19:in `process'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:14:in `processed'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activestorage (7.0.4) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:200:in `block in halting'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'

2023-02-01T22:47:11.215 app[8c8d29bc] mad [info] [f4a13a63-e385-4b4f-aab7-987e00311d80] activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-02-01T22:47:11.217 app[8c8d29bc] mad [info] F, [2023-02-01T22:47:11.217124 #540] FATAL -- : [d5a50b2a-8398-4fd7-a16c-e701a7003e45]

2023-02-01T22:47:11.220 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.213679 #540] INFO -- : [a44b2097-4e1f-41ab-a3aa-d2e0fda9f430] Disk Storage (0.1ms) Downloaded file from key: pth23g4vxm6i1wgq96rj2i1qvd2e

2023-02-01T22:47:11.228 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.228503 #540] INFO -- : [d5a50b2a-8398-4fd7-a16c-e701a7003e45] Completed 500 Internal Server Error in 11ms (ActiveRecord: 7.7ms | Allocations: 8109)

2023-02-01T22:47:11.238 app[8c8d29bc] mad [info] Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:es], :formats=>[:jpeg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.

2023-02-01T22:47:11.238 app[8c8d29bc] mad [info] Searched in:

2023-02-01T22:47:11.238 app[8c8d29bc] mad [info] * "/app/app/views"

2023-02-01T22:47:11.242 app[8c8d29bc] mad [info] Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:es], :formats=>[:jpeg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.

2023-02-01T22:47:11.244 app[8c8d29bc] mad [info] Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:es], :formats=>[:jpeg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.

2023-02-01T22:47:11.446 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.445702 #540] INFO -- : [8f93351f-161e-470c-9df3-e3d6036be06f] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWs0WVdNM05EbGxOaTAzWldNd0xUUTJNak10T0RabE5TMHhZbVl5WVdRMk0yVXlZelFHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--27285061f8dc3ae729895938d266a5ef629d23c8/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFINmFRSDYiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--eef2f1ecc00249301aae0d75648cfd6f46cfe223/RQP46.png" for 137.66.55.88 at 2023-02-01 22:47:11 +0000

2023-02-01T22:47:11.448 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.448469 #540] INFO -- : [8f93351f-161e-470c-9df3-e3d6036be06f] Processing by ActiveStorage::Representations::RedirectController#show as PNG

2023-02-01T22:47:11.449 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.448595 #540] INFO -- : [8f93351f-161e-470c-9df3-e3d6036be06f] Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWs0WVdNM05EbGxOaTAzWldNd0xUUTJNak10T0RabE5TMHhZbVl5WVdRMk0yVXlZelFHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--27285061f8dc3ae729895938d266a5ef629d23c8", "variation_key"=>"[FILTERED]", "filename"=>"RQP46"}

2023-02-01T22:47:11.449 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.447734 #540] INFO -- : [993ac9bf-4d5d-47ea-8146-2d739186fd27] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsyWlRRMk9HRmhNeTFpWldKa0xUUXhaakF0T1dWa05DMDFPVFE0TldZMk4yUmpPVGtHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--4ca09760ae4e53fbc021fd4a35d661a2c4549306/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hSeVpYTnBlbVZmZEc5ZmJHbHRhWFJiQjJrQitta0IrZz09IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--56044ff0268e8ed2ac6ec5e321d4c66df754c364/DU608.jfif" for 137.66.55.88 at 2023-02-01 22:47:11 +0000

2023-02-01T22:47:11.450 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.449729 #540] INFO -- : [993ac9bf-4d5d-47ea-8146-2d739186fd27] Processing by ActiveStorage::Representations::RedirectController#show as */*

2023-02-01T22:47:11.450 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.449865 #540] INFO -- : [993ac9bf-4d5d-47ea-8146-2d739186fd27] Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsyWlRRMk9HRmhNeTFpWldKa0xUUXhaakF0T1dWa05DMDFPVFE0TldZMk4yUmpPVGtHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--4ca09760ae4e53fbc021fd4a35d661a2c4549306", "variation_key"=>"[FILTERED]", "filename"=>"DU608"}

2023-02-01T22:47:11.450 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.446315 #540] INFO -- : [bfae282f-e006-4fea-a011-fba065304de2] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsyWkRjNU16VmlOQzAwTXpVeExUUXpOall0T1RFMll5MDBaVFk0WlRnNE1XTmlZbUlHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--580471fdf3ac316ebaac887a5f252ca0503b7934/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFINmFRSDYiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--0ff31629199242895b062e3bcdf7845c71d467da/106_106-Container%20-%2011000024%20-21000024.jpg" for 137.66.55.88 at 2023-02-01 22:47:11 +0000

2023-02-01T22:47:11.451 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.450747 #540] INFO -- : [bfae282f-e006-4fea-a011-fba065304de2] Processing by ActiveStorage::Representations::RedirectController#show as JPEG

2023-02-01T22:47:11.451 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.450817 #540] INFO -- : [bfae282f-e006-4fea-a011-fba065304de2] Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsyWkRjNU16VmlOQzAwTXpVeExUUXpOall0T1RFMll5MDBaVFk0WlRnNE1XTmlZbUlHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--580471fdf3ac316ebaac887a5f252ca0503b7934", "variation_key"=>"[FILTERED]", "filename"=>"106_106-Container - 11000024 -21000024"}

2023-02-01T22:47:11.451 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.446906 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsxT0RobU9HVm1NaTFoWm1OaUxUUXpOemt0T1dOaE9TMHpaakE1T1RVMU9UVXlNREVHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--604d6d62c88c4f16627fa255c3a76639b2145111/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hSeVpYTnBlbVZmZEc5ZmJHbHRhWFJiQjJrQitta0IrZz09IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--56044ff0268e8ed2ac6ec5e321d4c66df754c364/UK100.jfif" for 137.66.55.88 at 2023-02-01 22:47:11 +0000

2023-02-01T22:47:11.452 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.451741 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Processing by ActiveStorage::Representations::RedirectController#show as */*

2023-02-01T22:47:11.452 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.451804 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsxT0RobU9HVm1NaTFoWm1OaUxUUXpOemt0T1dOaE9TMHpaakE1T1RVMU9UVXlNREVHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--604d6d62c88c4f16627fa255c3a76639b2145111", "variation_key"=>"[FILTERED]", "filename"=>"UK100"}

2023-02-01T22:47:11.456 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.455660 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Disk Storage (0.2ms) Downloaded file from key: lof0v26wvjf3exlntkk6d81rgtuu

2023-02-01T22:47:11.458 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.458177 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.6ms | Allocations: 2610)

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] F, [2023-02-01T22:47:11.459350 #540] FATAL -- : [781abd44-588f-447b-93c2-fe9020e0200b]

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b]

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:150:in `rescue in stream'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:143:in `stream'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:29:in `block in download'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service.rb:163:in `instrument'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service/disk_service.rb:28:in `download'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/downloader.rb:32:in `download'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/downloader.rb:13:in `block in open'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/downloader.rb:24:in `open_tempfile'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/downloader.rb:12:in `open'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) lib/active_storage/service.rb:90:in `open'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) app/models/active_storage/blob.rb:301:in `open'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:19:in `process'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) app/models/active_storage/variant_with_record.rb:14:in `processed'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activestorage (7.0.4) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:200:in `block in halting'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'

2023-02-01T22:47:11.459 app[8c8d29bc] mad [info] [781abd44-588f-447b-93c2-fe9020e0200b] actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'

2023-02-01T22:47:11.462 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.457963 #540] INFO -- : [993ac9bf-4d5d-47ea-8146-2d739186fd27] Disk Storage (0.1ms) Downloaded file from key: dpo2e1twfssqoxd1grl28ahl0o42

2023-02-01T22:47:11.464 app[8c8d29bc] mad [info] [993ac9bf-4d5d-47ea-8146-2d739186fd27] activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-02-01T22:47:11.471 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.471061 #540] INFO -- : [781abd44-588f-447b-93c2-fe9020e0200b] Rendered errors/500.html.erb within layouts/error (Duration: 0.1ms | Allocations: 46)

2023-02-01T22:47:11.474 app[8c8d29bc] mad [info] I, [2023-02-01T22:47:11.467649 #540] INFO -- : [bfae282f-e006-4fea-a011-fba065304de2] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.2ms | Allocations: 3558)

2023-02-01T22:47:11.477 app[8c8d29bc] mad [info] Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:es], :formats=>[:jpeg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.
```

**Comment by ciscoLegrand** [comment]
Se han probado diferentes configuraciones en el fly.toml, añadiendo servicios, se ha creado la base de datos redis en fly, y no funcionaba.

en el último deploy, no da error y añade bien las imagenes y las renderiza.

Pendiente de monitorizar futuros deploys que siga funcionando igual

**Comment by ciscoLegrand** [comment]
problema al renderizar las imagenes es el **storage.yml**, que se modifica para desarrolo en local y no se cambia al construir la imagen antes del **deploy**.
